spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/easylink
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update